name : database2_workflow
on:
  push:
    paths:
      - 'DatabaseProj2/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3.5.3
      - name: Echo
        run: |
          echo " from database 2"