name : database1_workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup .NET core
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '6.0.401'
      - name: Setup sql project
        run: |
          dotnet new install Microsoft.Build.Sql.Templates
      - name: Build project
        run: |
          cd DatabaseProj1
          dotnet build DatabaseProj1.sqlproj